### ISSUE TITLE
Use CSS variables for general design

### ISSUE THREAD

**Issue by atjn** [ECDAR-AAU-SW-P5/Ecdar-GUI-Web#40]
We should create a declaration in [`+layout.svelte`](../blob/main/src/routes/%2Blayout.svelte) where we define all colors used in the app, along with font sizes and borders and so on. This will allow for easier control and overview of the theme we are using. It will also allow for future improvements, such as a dark mode.

I think it would be best if we try to add all necessary variables in one go, instead of adding them slowly as we discover that we need them. The latter method can quickly become a mess.

Declaration template:
```css
:global(:root) {
  --main-background-color: rgb(200 200 200);
  --main-font-color: rgb(20 20 20);
}
```

How to use the variables:
```css
p {
  color: var(--main-font-color);
}
```
